# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c317f1ac8e897e0ab9f93a4da66045b15f57f1fdf18451d092f93fd5faaf9b855eca270328e1072e1e6ae9ad5314abac5d2ec09c48a268e482817665e1ed14f

test:
  secret_key_base: 3033ca4973bb39e8c877b82e9edff25388825e13c245c42d1d70670442d1830298eef5e8fa286be96d51e37a501fe3cc19c6ef26da2aafbd2a6571b328cf9f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
